### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DavidGasparyan**
merge all unit test suite

### CODE REVIEW

**Review by KhachigJ — APPROVED** [review]
We can merge

**Review by saroshekhook — APPROVED** [review]
all good, go for the merging part

**Review by Seza-Garj — APPROVED** [review]
the code is mergeable

**Review by Anna-Gevorgyan — APPROVED** [review]
I approve

**Comment by DavidGasparyan** [comment]
Thank you all for your effort

**Pull request merged**
